# Generated by Django 2.2 on 2019-05-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_schema', '0002_auto_20190428_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsschema',
            name='schema',
            field=models.TextField(),
        ),
    ]
