# Generated by Django 2.2 on 2019-05-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190427_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ips',
            field=models.TextField(default=''),
        ),
    ]
